### ISSUE TITLE
패키지 구조 변경

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#38]
** 변경 사유 **
기존 패키지 구조가 공통된 클래스의 역할 끼리 모여 있지 않다고 생각 됩니다.
더 개선 된 클래스의 구조를 만들어야 할 것 같습니다.

** 변경 방법 **
자유롭게 댓글로 작성해 주세요

** 기타 **

**Comment by sungjiwoon** [comment]
뷰를 (1) (2) 선택지가 아닌 각 기능을 보여주는 뷰로 바꾸는건 어떨까요..? 어려울까요
DAO는 기존과 동일하게 가도될 것 같습니다. 
컨트롤러도 동일하게 가도될것 같습니다.
