### ISSUE TITLE
DTO의 사용

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#39]
** 변경 사유 **
원칙적으로는 DTO를 사용하는게 맞는 걸로 알고 있습니다. 입력받아 데이터를 전달하는 객체와, 조회해서 데이터를 가져오는 객체는 서로 다른 정보를 담고 있으니까요. 간단한게 TripDTO를 구현해 봤는데요. 어떻게 생각하시는지 궁금합니다.

** 변경 방법 **
회의 때 이 프로젝트에선 굳이 DTO를 사용하지 않아도 될 것 같다는 합의가 있었습니다.
혹시 개선 방법이 있다면 자유롭게 댓글을 남겨주세요

** 기타 **

**Comment by sungjiwoon** [comment]
저또한 기능이 단순하기도 하고 작은 규모이기 때문에 원칙에는 맞진 않지만 DTO를 사용하지 않아도 될 것 같습니다!

**Comment by whdgns5059** [comment]
넵 해당부분은 회의때 얘기한 것처럼 두도록 하는게 맞아 보이네요

**Comment by whdgns5059** [comment]
오늘 멘토링에서 멘토님께 여쭤보니 domain에 setter를 열어두는건 절대 하지 말고, DTO를 만드는게 맞다고 하시네요
DTO를 만드는게 맞는것 같습니다.

**Comment by sungjiwoon** [comment]
확인이요! DTO는 뷰에서 사용하고 도메인은 DAO에서 사용하는걸까요?

**Comment by ghrltjdtprbs** [comment]
그러면 DTO를 만드는 것이 좋을것 같네요!

**Comment by decten** [comment]
그럼 지금 리팩토링이 DTO, 예외 처리, 공통 부분 메소드랑 맞게 처리하는 일이 필요한거네요
예외처리를 종현님이 하신다고 하셨으니 DTO랑 공통 부분 메소드 분리를 다른 사람들이 나눠서 주말에 처리할까요?

**Comment by whdgns5059** [comment]
tripDto, ItineraryDto 추가해서 로직을 수정 했습니다.
