### ISSUE TITLE
예외처리

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#40]
** 변경 사유 **
입력의 예외처리에 대해 어떻게 할지 고민입니다. 모든 입력에 대해 input의 값을 검증하는 것이 올바른 방법입니다만. 이를 exception을 이용하면 다시 재입력 받는등의 행위가 복잡해지고 코드가 많이 지저분 해지죠.

그렇다고 모든 input에 대해 if문으로 해당 부분을 검증 하기도 마찬가지 입니다. 예외처리를 공통으로 처리하고 예외 발생시에 후속조치를 지정 할 수 있는 방법에 대해 고민해야 할 것 같습니다.

** 변경 방법 **
람다식을 이용해 예외처리를 반복 시킬 수 있을거 같습니다.
[람다식, 메서드 참조를 이용하여 예외 발생시 성공할 때 까지 반복 구현 - 함수형 인터페이스](https://dev-dongmoo.tistory.com/14)

** 기타 **

**Comment by whdgns5059** [comment]
변경방법에 써있는 방식으로
예외처리는 제가 담당해 보도록 하겠습니다.

**Comment by yeoni98** [comment]
입력한 여행 Id가 존재하지 않을 경우의 예외 처리는 수정해서 풀리퀘했습니다!

**Comment by decten** [comment]
orElseThrow 메소드를 사용하고 그 안에 저희가 정의한 에러처리 클래스가 동작하도록 하면 어떨까요?
스프링 필수 강의에서 보고 실습한 코드인데 복잡하거나 저희 상황이랑 안 맞으면 다른 방법을 다시 생각 해보겠습니다.
<img width="370" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/ToyProject1/assets/52107658/108fbab2-d7e2-42d0-8b6d-e1e27b2c44e4">
<img width="461" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/ToyProject1/assets/52107658/b0d19fe1-e774-41ee-b8fa-254684f568e2">

**Comment by whdgns5059** [comment]
지금은 Scanner 입력에서 정규식으로 처리를 했는데,
정규식으로 빠져나가는 경우가 있더라구요 (날짜를 24:00)으로 하면 정규식에선 빠져나감.
Date 클래스 같은곳에는 해당 방법을 적용 시켜보겠습니다. 감사합니다
