### ISSUE TITLE
싱글턴 패턴의 적용

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#41]
** 변경 사유 **
화면이동, Controller 호출, DAO호출은 사실 매번 인스턴스를 생성 할 필요가 없습니다. 객체의 값이 변경되지 않기 때문입니다. 이를 싱글턴 패턴을 이용한다면 메모리의 낭비를 줄 일 수 있을거라 생각합니다.

** 변경 방법 **
싱글턴 패턴의 적용

** 기타 **

**Comment by sungjiwoon** [comment]
저도 뷰와 DAO는 싱글톤 패턴 찬성합니다. 제가 아직은 잘 몰라서 그런데 컨트롤러 같은 경우는 저희가 뷰에 따라 따로 만들어서 해당 뷰에만 컨트롤러를 선언하기 때문에 싱글톤으로 해도 큰 차이가 있나요? 만약 뷰를 싱글톤으로 만든다 가정할 때, 컨트롤러는 싱글톤으로 하지 않아도 1번밖에 적재가 되지 않나요?

**Comment by whdgns5059** [comment]
네 그부분도 맞습니다. 현재 프로그램에선 해당 컨트롤러와 DAO는 호출을 한번만 하고 있어서, View가 싱글톤이면 Controller와 Dao도 1개 이상 생성되진 않을걸로 생각합니다.
프로젝트의 규모가 크다면 고려해 볼만 하겠지만 지금은 View만 싱글톤 패턴으로 생성 해도 될 거 같네요
메인화면 이동은 제 담당이었으니까 제가 수정해서 PR보내겠습니다.
