### ISSUE TITLE
반복작업의 메서드 분리

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#42]
** 변경 사유 **
예를 들면 현재 tripinput과 itineraryinput에서 둘다 여정을 입력받는 비슷한 작업이 반복 되고 있습니다. 또 trip의 목록을 보여주는 부분 역시 조회를 구현한 부분에서 동일하게 이뤄지고 있습니다. 이 부분을 적절하게 통합 할 수 있을 것 같습니다.

** 변경 방법 **
이부분은 담당하신 개발자 분들끼리 많은 소통이 필요 할 것 같습니다. 거의 비슷하긴 해도 약간씩 그 구현 방법이 다르기 때문에요.
여행입력과 여정입력 메뉴에서 여정을 입력받는 부분이나 여행목록을 출력하는 부분이 대표적인 케이스 같습니다.

** 기타 **

**Comment by sungjiwoon** [comment]
tripInputView에서 trip Input을 진행하고 Itinerary input view로 넘어가는건 어려울까요..?

**Comment by decten** [comment]
그럼 공통 부분을 인터페이스로 빼면 어떨까요

**Comment by sungjiwoon** [comment]
분리완료
