### ISSUE TITLE
변경 되지 않는 문자열들(파일 경로, 파일이름)의 처리

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/ToyProject1#43]
** 변경 사유 **
파일 경로나 컬럼명 같은 final String 변수 들이 몇몇 존재 하고 있습니다. 
이런 경로를 어떤 식으로 관리하는게 더 좋은 방안 일까요. 
간단하게 common 클래스에 static 으로 보관하는 방법이 생각납니다.

** 변경 방법 **
더 좋은 방법이 있다면 댓글에 자유롭게 작성해 주세요

** 기타 **

**Comment by sungjiwoon** [comment]
<img width="908" alt="스크린샷 2023-09-08 오후 2 28 34" src="https://github.com/FC-BE-ToyProject-Team6/ToyProject1/assets/59862752/1d3107f0-0661-468b-bd13-f74e4df1794e">

일단 한번 만들어서 DAO에 적용시켜봤는데 정상적으로 돌아가서요! 이런 방법은 괜찮으실까요?

**Comment by sungjiwoon** [comment]
<img width="818" alt="스크린샷 2023-09-08 오후 2 30 12" src="https://github.com/FC-BE-ToyProject-Team6/ToyProject1/assets/59862752/c85b8cf2-1378-4521-9c90-f195317a413d">

String.format 쓰면 숫자 들어가요! 다만 궁금한 점이 있는데, 디렉토리 path에도 /가 있는데 왜 한번더 / 붙이는지가 궁금합니다..!

**Comment by whdgns5059** [comment]
enum에 대해 생각해 봤지만 용도에 안맞는거 같고
만드신것 처럼 따로 클래스를 만들어서 관리하는게 좋은거 같습니다.

슬래시를 2개 쓰는이유는 저도 찾아봤는데요
깊게 파면 unix, dos, window 역사까지 가게 되는거 같습니다. 
대충 요약 해보면 OS별로 슬래시, 백슬래시를 쓰는법이 달랐었고 이걸 \\, \, / 등등 표현하는 등 방법이 다양했다고 하네요
지금은 이래저래 알아서 처리 해준다는 거 같습니다

java doc을 확인해보니 파고 들어가 보면
파일 경로를 만드는데 정규식으로 변환하는 부분이 있고, 거기서 알아서 \로 변경해 준다고 하네요

**Comment by sungjiwoon** [comment]
엇 그러면 static 으로 제가 fullPath까지 만든다음에 수정해서 PR 보내도될까요?

**Comment by whdgns5059** [comment]
넵
